In [28]:
import numpy as np

# Работа с векторами и матрицами в NumPy

## 1. Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: **np.random.normal**

Параметры функции:

>* **loc:** среднее нормального распределения (в нашем случае 1)
* **scale:** стандартное отклонение нормального распределения (в нашем случае 10)
* **size:** размер матрицы (в нашем случае (1000, 50))</p>


In [29]:
matrix = np.random.normal(loc=1, scale=10, size=(1000, 50))
print (matrix)

[[  3.30556571   1.62200339 -16.53272248 ...  -8.3074632   -1.73020218
   -5.50777566]
 [  8.47310422   0.56027738  -7.41797961 ...  14.63298242 -18.07630382
   -2.96452507]
 [ -2.12696629  11.44644796 -21.27869851 ...  11.20986704  -5.85917846
  -13.39616379]
 ...
 [  8.23025505  -1.19018736  -9.31854786 ...  -8.53558811   5.46615668
    4.01413041]
 [  9.82764103   7.32769519  -2.23686517 ...  -4.97127227   9.73553819
    3.96017539]
 [ 14.88934303  15.43163648  13.86588689 ...   9.53838232  -2.82036893
   21.40649896]]


## 2. Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: **np.mean**

Функция для вычисления стандартного отклонения: **np.std**

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [30]:
mean_matrix = np.mean(matrix, axis=0)
std = np.std(matrix, axis=0)
matrix_norm = ((matrix - mean_matrix)  / std)
print (matrix_norm)

[[ 1.89649053e-01  1.04399372e-01 -1.78083020e+00 ... -8.96538330e-01
  -2.79611257e-01 -6.21748868e-01]
 [ 6.91718634e-01  1.84595966e-03 -8.73609095e-01 ...  1.36830183e+00
  -1.86089287e+00 -3.67799928e-01]
 [-3.38166861e-01  1.05335448e+00 -2.25321321e+00 ...  1.03034810e+00
  -6.79038253e-01 -1.40942107e+00]
 ...
 [ 6.68123806e-01 -1.67233570e-01 -1.06277906e+00 ... -9.19060405e-01
   4.16546775e-01  3.29033552e-01]
 [ 8.23323213e-01  6.55519116e-01 -3.57915296e-01 ... -5.67166385e-01
   8.29556227e-01  3.23646029e-01]
 [ 1.31510989e+00  1.43828871e+00  1.24484594e+00 ...  8.65327515e-01
  -3.85071304e-01  2.06569826e+00]]


## 3. Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: **np.sum**

Аргументы аналогичны функциям **np.mean** и **np.std**.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции **np.nonzero**.



In [31]:
m = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [32]:
s = np.sum(m, axis=1)
print (np.nonzero(s > 10))

(array([1, 4, 5]),)


## 4. Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

Функция для генерации единичной матрицы: **np.eye**

Аргумент: число строк (или, что эквивалентно, столбцов).

Функция для вертикальной стыковки матриц: **np.vstack((A, B))**

In [33]:
a = np.eye(3)
b = np.eye(3)
print (a)
print ("\n")
print (b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
c = np.vstack((a, b))
print (c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
